name: testdatn
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cached_network_image: ^3.3.1
  http: ^1.2.2
  shared_preferences: ^2.4.2
  intl: ^0.19.0
  async: ^2.11.0
  fake_async: ^1.3.1
  leak_tracker: ^10.0.5
  material_color_utilities: ^0.11.1
  vm_service: ^14.3.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
    - assets/login_header.png
    - assets/images/anh1.png
    - assets/images/anh2.png
    - assets/images/anh3.png
    - assets/images/anh4.png
    - assets/images/anh5.png
    - assets/images/anh6.png
    - assets/images/spl1.jpg
    - assets/images/spl2.jpg
    - assets/images/spl3.jpg
    - assets/images/spl4.jpg
    - assets/icons/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/anh6.png"  # Đường dẫn tới file icon gốc của bạn
